config/routes.rb
Rails.application.routes.draw do
  resources :players
  resources :news
  resources :employees

  get 'home/index'
  get 'other/index'


  get '/home/turbo_frame_form' => 'home#turbo_frame_form', as: 'turbo_frame_form'
  post '/home/turbo_frame_submit' => 'home#turbo_frame_submit', as: 'turbo_frame_submit'
  post '/other/post_something' => 'other#post_something', as: 'post_something'

  # root to: "home#index"
  root "employees#index"



  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/employee.rb
class Employee < ApplicationRecord
    def self.search(query)
        if query
            employee = Employee.find_by(employee_name: query)
        else
            @employees = Employee.all
        end
    end
end

app/models/news.rb
class News < ApplicationRecord
end

app/models/player.rb
class Player < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :turbo_frame_request_variant
    private
    def turbo_frame_request_variant
        request.variant = :turbo_frame if turbo_frame_request?
    end
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  before_action :set_employee_params, only: %i[show edit update destroy]

  def index 
    if params[:query].present?
      @employees = Employee.where("employee_name LIKE ?", "%#{params[:query]}%")
    else
      @employees = Employee.all
    end
  end

  def new
    @employee = Employee.new
  end

  def create
    @employee = Employee.create(employee_params)
    if @employee.valid?
      flash[:errors] = 'Employee Created Successfully'
      redirect_to employees_path
    else
      flash[:errors] = @employee.errors.full_messages
      render :new
    end
  end

  def show; end

  def edit; end

  def update
    if @employee.update(employee_params)
      flash[:errors] = 'Employee Updated Successfully'
      redirect_to employee_path(@employee)
    else
      flash[:errors] = @employee.errors.full_messages
      redirect_to edit_employee_path
    end
  end

  def destroy
    if @employee.delete
      flash[:errors] = 'Employee Deleted Successfully'
      redirect_to root_path(@employee)
    else
      flash[:errors] = @employee.errors.full_messages
      redirect_to destroy_employee_path
    end
  end

  private

  def set_employee_params
    @employee = Employee.find(params[:id])
  end

  def employee_params
    params.require(:employee).permit(:employee_name, :gender, { hobbies: [] }, :query)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def turbo_frame_form
  end
  
  def turbo_frame_submit
     extracted_anynumber = params[:any][:anynumber]
     render :turbo_frame_form, status: :ok, locals: {anynumber: extracted_anynumber, comment: 'turbo_frame_submit ok' }
  end

end

app/controllers/news_controller.rb
class NewsController < ApplicationController
  before_action: set_news, only: %i[show, edit, update, destroy]
  def index
    news = News.all
  end

  def new
    news = News.new
  end

  def create
    news = News.create(news_params)
  end

  def show
  end

  def edit
  end

  def update
    news.update(news_params)
  end

  def destroy
    news.destroy
  end

  private

  def news_params
    params.require(news).permit(title, content)
  end

  def set_news
    news = News.find(params[:id])
  end
end

app/controllers/other_controller.rb
class OtherController < ApplicationController
  def index
  end
  def post_something
    respond_to do |format|
      format.turbo_stream {  }
    end
  end
end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: %i[ show edit update destroy ]

  # GET /players or /players.json
  def index
    if params[:query].present?
      @players = Player.where("name LIKE ?", "%#{params[:query]}%")
    else
      @players = Player.all
    end
    # remove after adding this in ApplicationController
    # if turbo_frame_request?
    #   render partial: "players", locals: { players: @players }
    # else
    #   render "index"
    # end  
  end

  # GET /players/1 or /players/1.json
  def show
  end

  # GET /players/new
  def new
    @player = Player.new
  end

  # GET /players/1/edit
  def edit
  end

  # POST /players or /players.json
  def create
    @player = Player.new(player_params)

    respond_to do |format|
      if @player.save
        format.html { redirect_to player_url(@player), notice: "Player was successfully created." }
        format.json { render :show, status: :created, location: @player }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /players/1 or /players/1.json
  def update
    respond_to do |format|
      if @player.update(player_params)
        format.html { redirect_to player_url(@player), notice: "Player was successfully updated." }
        format.json { render :show, status: :ok, location: @player }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @player.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /players/1 or /players/1.json
  def destroy
    @player.destroy

    respond_to do |format|
      format.html { redirect_to players_url, notice: "Player was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_player
      @player = Player.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def player_params
      params.require(:player).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/employees_helper.rb
module EmployeesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/news_helper.rb
module NewsHelper
end

app/helpers/other_helper.rb
module OtherHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/views/employees/_employee_list.html.erb
<turbo-frame id="employee_list">
  <table class="table table-info table-striped">
    <thead class="table-secondary">
      <tr>
        <th class="text-center">Id</th>
        <th class="text-center">Name</th>
        <th class="text-center">Hobbies</th>
        <th colspan="3" class="text-center">Action</th>
      </tr>
    </thead>
    <tbody>
      <% @employees.each do |e| %>
        <tr>
          <td class="text-center"><%= e.id %></td>
          <td class="text-center"><%= link_to e.employee_name, employee_path(e) %></td>
          <td class="text-center"><%= e.hobbies %></td>
          <td class="text-center"><%= button_to "Show", employee_path(e), method: :get, class: "btn-success border-0 rounded-pill shadow px-3 py-2" %></td>
          <td class="text-center"><%= button_to "Edit", edit_employee_path(e), method: :get, class: "btn-primary border-0 rounded-pill shadow px-3 py-2" %></td>
          <td class="text-center"><%= button_to "Delete", employee_path(e), method: :delete, data: { turbo_confirm: "Are you sure?" }, class: "btn-danger border-0 rounded-pill shadow px-3 py-2" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
</turbo-frame>

app/views/employees/_form.html.erb
<div class="card shadow" style="width: 36rem;">
<div class="card-body">
    <!--Error Message-->
    <% if flash[:errors] %>
    <% flash[:errors].each do |error| %>
        <p class="text-danger"><%= error %></p>
    <% end %>
    <% end %>
    <!-- Form Started Here -->
    <%= form_with model: @employee do |f| %>
    <%= f.label :employee_name, "Employee Name :", class:"mt-3" %>
    <%= f.text_field :employee_name ,placeholder: "Enter Employee's Name",class:"mb-2 form-control" %>
    <br>
    <!-- Radio Button For Gender -->
    <div class="form-group">
        <%= f.label "Gender :" %>
        <%= f.radio_button :gender, "male" %>
        <%= f.label :gender, "Male" %>
        <%= f.radio_button :gender, "female" %>
        <%= f.label :gender, "Female" %>
    </div>
    <br>
    <!-- Checkbox For Hobbies -->
    <div class="form-group">
        <%= f.label "Hobbies :" %>
        <%= f.check_box :hobbies, { multiple: true },"Reading", false %>
        <%= f.label :hobbies, "Reading" %>
        <%= f.check_box :hobbies, { multiple: true },"Drawing", false %>
        <%= f.label :hobbies, "Drawing" %>
        <%= f.check_box :hobbies, { multiple: true },"Travelling", false %>
        <%= f.label :hobbies, "Travelling" %>
    </div>
    <br>
    <%= f.submit "Save Employee", class:"btn-primary" %>
    <% end %>
</div>
</div>

app/views/employees/edit.html.erb
<div class="flex-column m-5">
    <h2>Employee Form</h1>
    <%= render "form" %>
</div>

app/views/employees/index.html.erb
<div class="flex-column m-5" style = "height: auto;">
  <h1 class="text-center"> Employees </h1>
  <div class="p-3">
    <%= form_with(url: employees_path, method: "GET") do |form| %>
    <%= form.label :query, "Search by name:" %>
    <%= form.text_field :query %>
    <%= form.submit 'Search', name: nil %>
    <% end %>
  </div>
    
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
  <!-- Employee Table -->
  <div>
  <%= render 'employee_list' %>
  </div>
  <div class="d-flex justify-content-center">
    <%= button_to "Add New Employee", new_employee_path, method: :get ,class:"btn-primary shadow p-3 m-3" %>
  </div>
</div>

app/views/employees/new.html.erb
<div class="flex-column m-5">
    <h2>Employee Form</h1>
    <%= render "form" %>
</div>

app/views/employees/show.html.erb
<!-- Employee Details Showing -->
<turbo-frame id="employee_list">

<div class="flex-column" style="height:100vh;">
  <!--Error Message-->
  <% if flash[:errors] %>
    <% flash.each do |name,message| %>
      <p class="text-danger"><%= message%></p>
    <% end %>
  <% end %>
  <div class="d-flex">
    <div class="m-5" >
      <div class="card bg-light border-warning shadow">
        <div class="card-body">
          <div class="card-header">
            <h2 class="text-center">Employee's Details</h2>
          </div>
          <div>
            <h2> &#10145; ID: <%= @employee.id %> </h2>
            <h2> &#10145; Name: <%= @employee.employee_name %> </h2>
            <h2> &#10145; Gender: <%= @employee.gender %> </h2>
            <h2> &#10145; Hobbies: <%= @employee.hobbies %> </h2>
          </div>
          <div class="d-flex">
            <%= button_to "Edit Employee" , edit_employee_path, method: :get ,class:"btn-success border-0 rounded-pill shadow p-2 m-2" %>
            <%= button_to "Delete Employee", employee_path, method: :delete ,class:"btn-danger border-0 rounded-pill shadow p-2 m-2" %>
            <%= button_to "View all Employee", employees_path,method: :get ,class:"btn-primary border-0 rounded-pill shadow p-2 m-2" %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>
</turbo-frame>

app/views/home/index.html.erb
<h1>This is Rails Hotwire home page</h1>
<div><%= link_to "Enter to other page", other_index_path %></div>

<%= turbo_frame_tag 'anyframe' do %>        
  <div>
      <h2>Home view</h2>
      <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
          <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
          <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
          <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
      <% end %>
  <div>
<% end %>

app/views/home/turbo_frame_form.html.erb
<section>

    <%= turbo_frame_tag 'anyframe' do %>
            
      <div>
          <h2>Frame view</h2>
          <%= form_with scope: :any, url: turbo_frame_submit_path, local: true do |form| %>
              <%= form.label :anynumber, 'Type an integer (odd or even)', 'class' => 'my-0  d-inline'  %>
              <%= form.text_field :anynumber, type: 'number', 'required' => 'true', 'value' => "#{local_assigns[:anynumber] || 0}",  'aria-describedby' => 'anynumber' %>
              <%= form.submit 'Submit this number', 'id' => 'submit-number' %>
          <% end %>
      </div>
      <div>
        <h2>Data of the view</h2>
        <pre style="font-size: .7rem;"><%= JSON.pretty_generate(local_assigns) %></pre> 
      </div>
      
    <% end %>

</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>HotwireStimulusTurbo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <!--Bootstrap CDN  -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <!-- JavaScript Bundle with Popper -->
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  
  <body>
    <%= yield %>
  </body>
</html>

app/views/news/create.html.erb
<h1>News#create</h1>
<p>Find me in app/views/news/create.html.erb</p>

app/views/news/destroy.html.erb
<h1>News#destroy</h1>
<p>Find me in app/views/news/destroy.html.erb</p>

app/views/news/edit.html.erb
<h1>News#edit</h1>
<p>Find me in app/views/news/edit.html.erb</p>

app/views/news/index.html.erb
<h1>News#index</h1>
<p>Find me in app/views/news/index.html.erb</p>

app/views/news/new.html.erb
<h1>News#new</h1>
<p>Find me in app/views/news/new.html.erb</p>

app/views/news/show.html.erb
<h1>News#show</h1>
<p>Find me in app/views/news/show.html.erb</p>

app/views/news/update.html.erb
<h1>News#update</h1>
<p>Find me in app/views/news/update.html.erb</p>

app/views/other/index.html.erb
<h1>This is Another page</h1>
<div><%= link_to "Enter to home page", root_path %></div>

<div style="margin-top: 3rem;">
  <%= form_with scope: :any, url: post_something_path do |form| %>
      <%= form.submit 'Post any message' %>
  <% end %>
  <turbo-frame id="messages">
    <div>An empty message</div>
  </turbo-frame>
</div>

app/views/other/post_something.turbo_stream.erb
<turbo-stream action="replace" target="messages">
  <template>
    <div id="message_1">This changes the existing message!</div>
  </template>
</turbo-stream>

app/views/players/_form.html.erb
<%= form_with(model: player) do |form| %>
  <% if player.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(player.errors.count, "error") %> prohibited this player from being saved:</h2>

      <ul>
        <% player.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/players/_player.html.erb
<div id="<%= dom_id player %>">
  <p>
    <%= player.name %> <%= link_to "View Player", player_path(player) %>
  </p>
</div>

app/views/players/_players.html.erb
<%= turbo_frame_tag "players" do %>
  <%= render players %>
<% end %>

app/views/players/edit.html.erb
<h1>Editing player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Show this player", @player %> |
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/index.html+turbo_frame.erb
<%= turbo_frame_tag "players" do %>
  <%= render @players %>
<% end %>

app/views/players/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Players</h1>
<%= form_with(url: players_path, method: "GET", data: { turbo_frame: "players" }) do |form| %>
  <%= form.label :query, "Search by name:" %>
  <%= form.text_field :query %>
  <%= form.submit 'Search', name: nil %>
<% end %>

<!-- Rendering the new partial here -->
<%= render "players", players: @players %>

<%= link_to "New player", new_player_path %>

app/views/players/new.html.erb
<h1>New player</h1>

<%= render "form", player: @player %>

<br>

<div>
  <%= link_to "Back to players", players_path %>
</div>

app/views/players/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @player %>

<div>
  <%= link_to "Edit this player", edit_player_path(@player) %> |
  <%= link_to "Back to players", players_path %>

  <%= button_to "Destroy this player", @player, method: :delete %>
</div>